exp_name: 2feats
model_name: SPELL2FEATS
graph_name: RESNET18-TSM-ALL_csi_30.0_0.9
training_sets:
- WASDtrainLaugh
- WASDvalLaugh
- train
test_sets:
- test
loss_name: bce_logit
use_spf: true
use_ref: false
num_modality: 2
channel1: 64
channel2: 16
proj_dim: 64
final_dim: 1
num_att_heads: 0
dropout: 0.3
lr: 0.0005
wd: 0
batch_size: 16
sch_param: 10
num_epoch: 80
csv_path: /home/brooke/Downloads/annotations.csv
multiclass: false
classIndex: 2
positiveLabels:
- speaking_to_pepper
- speaking_to_human
useTwoViews: Back
gender: true
gaze: true
twoView: false
numPredSpeakers: false
laugh_not_speech: false
landmarks: false
