exp_name: byplayAudioOnly
model_name: SPELLBYPLAYAUDIOONLY
graph_name: RESNET18-TSM-ALL2_csi_30.0_0.9
loss_name: ce
use_spf: true
use_ref: false
num_modality: 2
channel1: 64
channel2: 16
proj_dim: 64
final_dim: 4
num_att_heads: 0
dropout: 0.3
lr: 0.0005
wd: 0
batch_size: 16
sch_param: 10
num_epoch: 90
root_data: ./data
root_result: ./results

training_sets: ["train"]
test_sets: ["test"]

gender: True
gaze: True
twoView: False
numPredSpeakers: False

csv_path: "/home2/bstephenson/GraVi-T/annotations.csv"
