from .spell import SPELL
from .spellByplay import SPELLBYPLAY
from .spellByplayGaze import SPELLBYPLAYGAZE
from .spellByplayLand import SPELLBYPLAYLAND
from .spell2FeatsByplay import SPELLBYPLAY2FEATS
from .spellByplayAudioOnly import SPELLBYPLAYAUDIOONLY
from .spellVisOnlyByplay import SPELLVISONLYBYPLAY
from .spellByplayGaze2view import SPELLBYPLAYGAZE2VIEWS
from .spellLandmarks import SPELLLAND
from .spellSpeakEmbGend import SPELLSPEAKEMB