from .spell import SPELL
from .spellByplay import SPELLBYPLAY
from .spellByplayGaze import SPELLBYPLAYGAZE
from .spellByplayLand import SPELLBYPLAYLAND
from .spell2FeatsByplay import SPELLBYPLAY2FEATS
from .spellByplayAudioOnly import SPELLBYPLAYAUDIOONLY
from .spellVisOnlyByplay import SPELLVISONLYBYPLAY
from .spellLandmarks import SPELLLAND
from .spellSpeakEmbGend import SPELLSPEAKEMB
from .spellBasicCausal import SPELLFORWARD
from .spellGaze import SPELLGAZE
from .spell2Feats import SPELL2FEATS
